networks:
  bytewave-network:
    external: true

services:
  bytewave:
    container_name: bytewave
    build: .
    restart: unless-stopped

    env_file:
      - .env

    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SERVER_URL: https://bytewave.vrugle.com
      DATABASE_URI: postgres://bwave:bwave@postgres-prod:5432/bwave

    networks:
      - bytewave-network

    expose:
      - "3000"
