/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    contacts: Contact;
    'company-faqs': CompanyFaq;
    'professional-faqs': ProfessionalFaq;
    posts: Post;
    placements: Placement;
    'client-quotes': ClientQuote;
    'success-videos': SuccessVideo;
    certifications: Certification;
    referrers: Referrer;
    referrals: Referral;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    'company-faqs': CompanyFaqsSelect<false> | CompanyFaqsSelect<true>;
    'professional-faqs': ProfessionalFaqsSelect<false> | ProfessionalFaqsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    placements: PlacementsSelect<false> | PlacementsSelect<true>;
    'client-quotes': ClientQuotesSelect<false> | ClientQuotesSelect<true>;
    'success-videos': SuccessVideosSelect<false> | SuccessVideosSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    referrers: ReferrersSelect<false> | ReferrersSelect<true>;
    referrals: ReferralsSelect<false> | ReferralsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-stats': SiteStat;
    homepage: Homepage;
    'site-settings': SiteSetting;
    'track-record': TrackRecord;
    'legal-page': LegalPage;
    'referral-settings': ReferralSetting;
  };
  globalsSelect: {
    'site-stats': SiteStatsSelect<false> | SiteStatsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'track-record': TrackRecordSelect<false> | TrackRecordSelect<true>;
    'legal-page': LegalPageSelect<false> | LegalPageSelect<true>;
    'referral-settings': ReferralSettingsSelect<false> | ReferralSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admin: everything, incl. accounts, site settings and leads. Editor: content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  type: 'talent' | 'enterprise' | 'lead' | 'newsletter';
  name?: string | null;
  email: string;
  role?: string | null;
  experience?: string | null;
  company?: string | null;
  headcount?: string | null;
  stack?: string | null;
  message?: string | null;
  /**
   * Which surface the lead came from (e.g. footer:/companies). Derived server-side in the /leads route, never sent by the browser.
   */
  source?: string | null;
  /**
   * Keyed hash of the submitter's IP, used to rate limit.
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The FAQ accordion on /companies.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-faqs".
 */
export interface CompanyFaq {
  id: number;
  question: string;
  answer: string;
  /**
   * Lower shows first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The FAQ accordion on /professionals.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "professional-faqs".
 */
export interface ProfessionalFaq {
  id: number;
  question: string;
  answer: string;
  /**
   * Lower shows first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Auto-generated 7-char hex id used in the URL.
   */
  articleId?: string | null;
  title: string;
  tag: string;
  /**
   * Sort order for /insights and lastModified in sitemap.xml. Set this; the display date below is only what readers see.
   */
  publishedAt: string;
  /**
   * Display date as it appears on the article, e.g. "October 12, 2026". Leave blank to format Published at.
   */
  date?: string | null;
  updated?: boolean | null;
  readTime: string;
  /**
   * Optional header image, also used as the social preview. 16:9 works best.
   */
  cover?: (number | null) | Media;
  excerpt: string;
  author: string;
  authorTitle?: string | null;
  authorBio?: string | null;
  authorLinkedIn?: string | null;
  /**
   * Square headshot. Optional.
   */
  authorAvatar?: (number | null) | Media;
  /**
   * Rich text. Type markdown shortcuts (## heading, **bold**, - list, > quote, ```code) and they convert live, or paste markdown.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Rendered as an accordion where a "## Frequently asked questions" heading appears in the body.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placements".
 */
export interface Placement {
  id: number;
  role: string;
  stack: string;
  candidate: string;
  /**
   * Company domain for logo.dev, e.g. stripe.com.
   */
  company: string;
  companyName: string;
  location: string;
  pay: string;
  status: 'Placed' | 'Interviewing' | 'Offer' | 'Negotiating';
  /**
   * Lower shows first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-quotes".
 */
export interface ClientQuote {
  id: number;
  name: string;
  /**
   * e.g. VP Engineering
   */
  title?: string | null;
  company: string;
  /**
   * Company domain for logo.dev, e.g. stripe.com.
   */
  domain: string;
  quote: string;
  row?: ('one' | 'two') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-videos".
 */
export interface SuccessVideo {
  id: number;
  name: string;
  /**
   * e.g. Backend Developer
   */
  role?: string | null;
  company: string;
  /**
   * Company domain for logo.dev, e.g. stripe.com.
   */
  domain: string;
  /**
   * e.g. 02:45
   */
  duration?: string | null;
  /**
   * Optional. 16:9 works best. Without one the card shows the name and role on a plain background.
   */
  thumbnail?: (number | null) | Media;
  row?: ('one' | 'two') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  code: string;
  ref: string;
  year: string;
  label: string;
  description: string;
  /**
   * logo.dev name/domain, e.g. iso, gdpr, e-verify.
   */
  logoName: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who refer leads. Share their link as /r/<code>; totals are computed from the Referrals collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrers".
 */
export interface Referrer {
  id: number;
  name: string;
  email: string;
  /**
   * Auto-generated. The share link is /r/<code>.
   */
  code?: string | null;
  /**
   * A suspended referrer's link stops attributing new referrals.
   */
  status: 'active' | 'suspended';
  /**
   * Per-referral reward for this referrer. Leave blank to use the default in Referral Settings.
   */
  rewardOverride?: number | null;
  /**
   * Times the share link has been opened.
   */
  clicks?: number | null;
  /**
   * All attributed referrals.
   */
  totalReferrals?: number | null;
  /**
   * Referrals marked qualified.
   */
  qualifiedReferrals?: number | null;
  /**
   * Sum of rewards across qualified referrals.
   */
  totalRewards?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One row per lead attributed to a referrer. Only qualified rows count towards rewards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals".
 */
export interface Referral {
  id: number;
  referrer: number | Referrer;
  /**
   * The lead this referral brought in.
   */
  contact?: (number | null) | Contact;
  /**
   * Rewards only count once qualified, so a spam lead can be rejected without inflating a payout.
   */
  status: 'pending' | 'qualified' | 'rejected';
  /**
   * Snapshot of the reward when this referral qualified, so later rate changes do not rewrite history.
   */
  rewardAmount?: number | null;
  /**
   * Marked by hand once the reward has been paid.
   */
  paidOut?: boolean | null;
  /**
   * Where the referred visitor landed.
   */
  landingPath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'company-faqs';
        value: number | CompanyFaq;
      } | null)
    | ({
        relationTo: 'professional-faqs';
        value: number | ProfessionalFaq;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'placements';
        value: number | Placement;
      } | null)
    | ({
        relationTo: 'client-quotes';
        value: number | ClientQuote;
      } | null)
    | ({
        relationTo: 'success-videos';
        value: number | SuccessVideo;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'referrers';
        value: number | Referrer;
      } | null)
    | ({
        relationTo: 'referrals';
        value: number | Referral;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  email?: T;
  role?: T;
  experience?: T;
  company?: T;
  headcount?: T;
  stack?: T;
  message?: T;
  source?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-faqs_select".
 */
export interface CompanyFaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "professional-faqs_select".
 */
export interface ProfessionalFaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  articleId?: T;
  title?: T;
  tag?: T;
  publishedAt?: T;
  date?: T;
  updated?: T;
  readTime?: T;
  cover?: T;
  excerpt?: T;
  author?: T;
  authorTitle?: T;
  authorBio?: T;
  authorLinkedIn?: T;
  authorAvatar?: T;
  content?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placements_select".
 */
export interface PlacementsSelect<T extends boolean = true> {
  role?: T;
  stack?: T;
  candidate?: T;
  company?: T;
  companyName?: T;
  location?: T;
  pay?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-quotes_select".
 */
export interface ClientQuotesSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  company?: T;
  domain?: T;
  quote?: T;
  row?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-videos_select".
 */
export interface SuccessVideosSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  domain?: T;
  duration?: T;
  thumbnail?: T;
  row?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  code?: T;
  ref?: T;
  year?: T;
  label?: T;
  description?: T;
  logoName?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrers_select".
 */
export interface ReferrersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  code?: T;
  status?: T;
  rewardOverride?: T;
  clicks?: T;
  totalReferrals?: T;
  qualifiedReferrals?: T;
  totalRewards?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals_select".
 */
export interface ReferralsSelect<T extends boolean = true> {
  referrer?: T;
  contact?: T;
  status?: T;
  rewardAmount?: T;
  paidOut?: T;
  landingPath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-stats".
 */
export interface SiteStat {
  id: number;
  stats?:
    | {
        value: number;
        decimals: number;
        suffix?: string | null;
        label: string;
        note: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  manifestoHeadline?: string | null;
  manifestoBody?: string | null;
  manifestoPoints?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Large scroll-revealed statement. Wrap the brand name in **double asterisks** to colour it.
   */
  agentParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  storyPanels?:
    | {
        eyebrow?: string | null;
        line1: string;
        /**
         * Second headline line. Wrap a word in **asterisks** to brand-colour it.
         */
        line2?: string | null;
        detail: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wrap a word in **asterisks** to brand-colour it.
   */
  ctaHeadline?: string | null;
  ctaBody?: string | null;
  ctaResponseNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tagline?: string | null;
  legalLine?: string | null;
  address?: string | null;
  navCtaLabel?: string | null;
  region?: string | null;
  /**
   * Leave empty to use the built-in footer. These links also feed sitemap.xml, so only point at pages or sections that exist.
   */
  footerGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Site-relative path, e.g. /services#pricing.
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown in the footer. Leave empty to hide the row.
   */
  socials?:
    | {
        label: string;
        /**
         * Full profile URL, including https://.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Default metadata for pages that don't set their own. Per-page titles/descriptions still override these.
   */
  seo?: {
    /**
     * Default <title> / og:title.
     */
    metaTitle?: string | null;
    /**
     * Default meta description / og:description.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated meta keywords.
     */
    keywords?: string | null;
    /**
     * Default social-share (Open Graph) image.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "track-record".
 */
export interface TrackRecord {
  id: number;
  /**
   * Headline numbers above the chart.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One point per year, in order, for the line chart.
   */
  growth?:
    | {
        year: string;
        value: number;
        /**
         * Optional tag, e.g. YTD.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-page".
 */
export interface LegalPage {
  id: number;
  /**
   * Legal entity name, e.g. Bytewave, Inc.
   */
  entity?: string | null;
  /**
   * Shown on the cover sheet, e.g. "2026.08".
   */
  version?: string | null;
  /**
   * Effective date as you want it displayed, e.g. "15 August 2026".
   */
  effective?: string | null;
  /**
   * e.g. State of Delaware, USA
   */
  governingLaw?: string | null;
  /**
   * One per policy. Order here is the order on the page and in the contents list.
   */
  documents?:
    | {
        /**
         * Anchor used by the footer link, e.g. "privacy" for /legal#privacy. Changing it breaks that link.
         */
        id: string;
        /**
         * Reference code, e.g. "DOC-01".
         */
        ref: string;
        /**
         * Short label for the contents list.
         */
        eyebrow: string;
        title: string;
        summary: string;
        clauses?:
          | {
              /**
               * Clause number, e.g. "1.1".
               */
              n: string;
              heading: string;
              paragraphs?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-settings".
 */
export interface ReferralSetting {
  id: number;
  /**
   * Reward per qualified referral, unless a referrer has an override.
   */
  defaultReward: number;
  /**
   * Display only, e.g. USD. No payments are processed.
   */
  currency: string;
  /**
   * How long after clicking a referral link a lead is still attributed.
   */
  cookieDays: number;
  /**
   * Shown under the referral form on /services#referral. Leave blank to hide.
   */
  terms?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-stats_select".
 */
export interface SiteStatsSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        decimals?: T;
        suffix?: T;
        label?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  manifestoHeadline?: T;
  manifestoBody?: T;
  manifestoPoints?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  agentParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  storyPanels?:
    | T
    | {
        eyebrow?: T;
        line1?: T;
        line2?: T;
        detail?: T;
        id?: T;
      };
  ctaHeadline?: T;
  ctaBody?: T;
  ctaResponseNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tagline?: T;
  legalLine?: T;
  address?: T;
  navCtaLabel?: T;
  region?: T;
  footerGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "track-record_select".
 */
export interface TrackRecordSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  growth?:
    | T
    | {
        year?: T;
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-page_select".
 */
export interface LegalPageSelect<T extends boolean = true> {
  entity?: T;
  version?: T;
  effective?: T;
  governingLaw?: T;
  documents?:
    | T
    | {
        id?: T;
        ref?: T;
        eyebrow?: T;
        title?: T;
        summary?: T;
        clauses?:
          | T
          | {
              n?: T;
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-settings_select".
 */
export interface ReferralSettingsSelect<T extends boolean = true> {
  defaultReward?: T;
  currency?: T;
  cookieDays?: T;
  terms?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}